### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Before expanding the derives, I have ensured it compiles on the latest idb.

### CODE REVIEW

**Comment by LucaCappelletti94** [comment]
While the changes I have made to update from the older `idb` seemed reasonable to me, I am still getting these errors. If you happen to have any hint regarding what may be causing them, I would appreciate your suggestions.

```
running 17 tests

test web::test_scan_keys_by_index ... FAIL
test web::test_scan_by_index ... FAIL
test web::test_get_all_keys_by_index ... ok
test web::test_get_all_by_index ... ok
test web::test_get_key_by_index ... ok
test web::test_get_by_index ... ok
test web::test_count_by_index ... ok
test web::test_unique_index ... ok
test web::test_delete ... ok
test web::test_scan_keys ... FAIL
test web::test_scan ... FAIL
test web::test_get_all_keys ... ok
test web::test_get_all ... ok
test web::test_count ... ok
test web::test_value_update ... ok
test web::test_value_add ... ok
test web::test_db_creation_and_deletion ... ok

failures:

---- web::test_scan_keys_by_index output ----
    error output:
        panicked at deli/tests/web.rs:745:10:
        called `Result::unwrap()` on an `Err` value: IndexedDbError(CursorAdvanceFailed(JsValue(InvalidStateError: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
        Error: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
            at http://127.0.0.1:8000/wasm-bindgen-test:742:25
            at handleError (http://127.0.0.1:8000/wasm-bindgen-test:352:18)
            at imports.wbg.__wbg_advance_0922866a23942467 (http://127.0.0.1:8000/wasm-bindgen-test:741:70)
            at web-fc40808d64b3182b.wasm.web_sys::features::gen_IdbCursor::IdbCursor::advance::hcf4c1013bbf9b4f9 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1273]:0x139cf4)
            at web-fc40808d64b3182b.wasm.idb::cursor::key_cursor::KeyCursor::advance::h5c7ef9410f6e6deb (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[800]:0x10bd8d)
            at web-fc40808d64b3182b.wasm.deli::key_cursor::KeyCursor<M>::advance::{{closure}}::hc88d876bdbfcc33a (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[341]:0xaea7c)
            at web-fc40808d64b3182b.wasm.deli::index::Index<M,T>::scan_keys::{{closure}}::h9997f283825c748f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[185]:0x50d47)
            at web-fc40808d64b3182b.wasm.web::test_scan_keys_by_index::{{closure}}::h85524fbb5807eeaf (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[159]:0x12f95)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::hcfc1aa3e3505137f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[884]:0x11637d)
            at web-fc40808d64b3182b.wasm.<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::hdc305cc356b51a79 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1993]:0x162354))))
        
        Stack:
        
        Error
            at http://127.0.0.1:8000/wasm-bindgen-test:633:21
            at logError (http://127.0.0.1:8000/wasm-bindgen-test:231:18)
            at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:8000/wasm-bindgen-test:632:66)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::Error::new::h0f3292be2f8d6e40 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3105]:0x1847aa)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook_impl::h5ccc83ef2fb241d3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1002]:0x123218)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook::h99d3469934819030 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[4469]:0x19abe8)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h5a5be30db70aa9af (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2717]:0x17b2e9)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x154293)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
        
        
    
    JS exception that was thrown:
        RuntimeError: unreachable
            at web-fc40808d64b3182b.wasm.__rust_start_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5419]:0x1a30cc)
            at web-fc40808d64b3182b.wasm.rust_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5299]:0x1a2ba7)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x1542be)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
            at web-fc40808d64b3182b.wasm.rust_begin_unwind (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3314]:0x188b7a)
            at web-fc40808d64b3182b.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3475]:0x18bb9f)
            at web-fc40808d64b3182b.wasm.core::result::unwrap_failed::h472431483d5eea7f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2487]:0x1748f6)
            at web-fc40808d64b3182b.wasm.web::test_scan_keys_by_index::{{closure}}::h85524fbb5807eeaf (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[159]:0x13154)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::hcfc1aa3e3505137f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[884]:0x11637d)

---- web::test_scan_by_index output ----
    error output:
        panicked at deli/tests/web.rs:680:10:
        called `Result::unwrap()` on an `Err` value: IndexedDbError(CursorAdvanceFailed(JsValue(InvalidStateError: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
        Error: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
            at http://127.0.0.1:8000/wasm-bindgen-test:742:25
            at handleError (http://127.0.0.1:8000/wasm-bindgen-test:352:18)
            at imports.wbg.__wbg_advance_0922866a23942467 (http://127.0.0.1:8000/wasm-bindgen-test:741:70)
            at web-fc40808d64b3182b.wasm.web_sys::features::gen_IdbCursor::IdbCursor::advance::hcf4c1013bbf9b4f9 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1273]:0x139cf4)
            at web-fc40808d64b3182b.wasm.idb::cursor::value_cursor::Cursor::advance::h58afe1064f0393e8 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[785]:0x109f34)
            at web-fc40808d64b3182b.wasm.deli::cursor::Cursor<M>::advance::{{closure}}::hbcc4dab61f7b46fd (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[342]:0xaf002)
            at web-fc40808d64b3182b.wasm.deli::index::Index<M,T>::scan::{{closure}}::ha7cd35234664bb8e (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[175]:0x41518)
            at web-fc40808d64b3182b.wasm.web::test_scan_by_index::{{closure}}::h508aa87e28954bea (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[158]:0xeea3)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::h031ccb8856af14dd (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[872]:0x114c25)
            at web-fc40808d64b3182b.wasm.<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::he040c95cbf07b43d (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1994]:0x16240f))))
        
        Stack:
        
        Error
            at http://127.0.0.1:8000/wasm-bindgen-test:633:21
            at logError (http://127.0.0.1:8000/wasm-bindgen-test:231:18)
            at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:8000/wasm-bindgen-test:632:66)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::Error::new::h0f3292be2f8d6e40 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3105]:0x1847aa)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook_impl::h5ccc83ef2fb241d3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1002]:0x123218)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook::h99d3469934819030 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[4469]:0x19abe8)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h5a5be30db70aa9af (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2717]:0x17b2e9)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x154293)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
        
        
    
    JS exception that was thrown:
        RuntimeError: unreachable
            at web-fc40808d64b3182b.wasm.__rust_start_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5419]:0x1a30cc)
            at web-fc40808d64b3182b.wasm.rust_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5299]:0x1a2ba7)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x1542be)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
            at web-fc40808d64b3182b.wasm.rust_begin_unwind (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3314]:0x188b7a)
            at web-fc40808d64b3182b.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3475]:0x18bb9f)
            at web-fc40808d64b3182b.wasm.core::result::unwrap_failed::h472431483d5eea7f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2487]:0x1748f6)
            at web-fc40808d64b3182b.wasm.web::test_scan_by_index::{{closure}}::h508aa87e28954bea (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[158]:0xf062)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::h031ccb8856af14dd (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[872]:0x114c25)

---- web::test_scan_keys output ----
    error output:
        panicked at deli/tests/web.rs:350:10:
        called `Result::unwrap()` on an `Err` value: IndexedDbError(CursorAdvanceFailed(JsValue(InvalidStateError: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
        Error: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
            at http://127.0.0.1:8000/wasm-bindgen-test:742:25
            at handleError (http://127.0.0.1:8000/wasm-bindgen-test:352:18)
            at imports.wbg.__wbg_advance_0922866a23942467 (http://127.0.0.1:8000/wasm-bindgen-test:741:70)
            at web-fc40808d64b3182b.wasm.web_sys::features::gen_IdbCursor::IdbCursor::advance::hcf4c1013bbf9b4f9 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1273]:0x139cf4)
            at web-fc40808d64b3182b.wasm.idb::cursor::key_cursor::KeyCursor::advance::h5c7ef9410f6e6deb (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[800]:0x10bd8d)
            at web-fc40808d64b3182b.wasm.deli::key_cursor::KeyCursor<M>::advance::{{closure}}::hc88d876bdbfcc33a (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[341]:0xaea7c)
            at web-fc40808d64b3182b.wasm.deli::store::Store<M>::scan_keys::{{closure}}::h1c2e15ef545e6c87 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[186]:0x5257f)
            at web-fc40808d64b3182b.wasm.web::test_scan_keys::{{closure}}::hdb5c1bf5c146c0c8 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[160]:0x16822)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::h9a9b5c3022ad2ac1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[879]:0x1159c3)
            at web-fc40808d64b3182b.wasm.<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::hb7ce4d33f91034aa (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1989]:0x162068))))
        
        Stack:
        
        Error
            at http://127.0.0.1:8000/wasm-bindgen-test:633:21
            at logError (http://127.0.0.1:8000/wasm-bindgen-test:231:18)
            at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:8000/wasm-bindgen-test:632:66)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::Error::new::h0f3292be2f8d6e40 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3105]:0x1847aa)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook_impl::h5ccc83ef2fb241d3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1002]:0x123218)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook::h99d3469934819030 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[4469]:0x19abe8)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h5a5be30db70aa9af (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2717]:0x17b2e9)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x154293)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
        
        
    
    JS exception that was thrown:
        RuntimeError: unreachable
            at web-fc40808d64b3182b.wasm.__rust_start_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5419]:0x1a30cc)
            at web-fc40808d64b3182b.wasm.rust_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5299]:0x1a2ba7)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x1542be)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
            at web-fc40808d64b3182b.wasm.rust_begin_unwind (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3314]:0x188b7a)
            at web-fc40808d64b3182b.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3475]:0x18bb9f)
            at web-fc40808d64b3182b.wasm.core::result::unwrap_failed::h472431483d5eea7f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2487]:0x1748f6)
            at web-fc40808d64b3182b.wasm.web::test_scan_keys::{{closure}}::hdb5c1bf5c146c0c8 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[160]:0x169dd)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::h9a9b5c3022ad2ac1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[879]:0x1159c3)

---- web::test_scan output ----
    error output:
        panicked at deli/tests/web.rs:260:10:
        called `Result::unwrap()` on an `Err` value: IndexedDbError(CursorAdvanceFailed(JsValue(InvalidStateError: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
        Error: Failed to execute 'advance' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
            at http://127.0.0.1:8000/wasm-bindgen-test:742:25
            at handleError (http://127.0.0.1:8000/wasm-bindgen-test:352:18)
            at imports.wbg.__wbg_advance_0922866a23942467 (http://127.0.0.1:8000/wasm-bindgen-test:741:70)
            at web-fc40808d64b3182b.wasm.web_sys::features::gen_IdbCursor::IdbCursor::advance::hcf4c1013bbf9b4f9 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1273]:0x139cf4)
            at web-fc40808d64b3182b.wasm.idb::cursor::value_cursor::Cursor::advance::h58afe1064f0393e8 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[785]:0x109f34)
            at web-fc40808d64b3182b.wasm.deli::cursor::Cursor<M>::advance::{{closure}}::hbcc4dab61f7b46fd (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[342]:0xaf002)
            at web-fc40808d64b3182b.wasm.deli::store::Store<M>::scan::{{closure}}::he3ffc2ff39e2edff (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[176]:0x4329f)
            at web-fc40808d64b3182b.wasm.web::test_scan::{{closure}}::hb68f83c66e78fce2 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[156]:0x497f)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::hdf52bf0309b8b90a (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[885]:0x11656f)
            at web-fc40808d64b3182b.wasm.<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::h7a78cc9444ab8a57 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1988]:0x161fad))))
        
        Stack:
        
        Error
            at http://127.0.0.1:8000/wasm-bindgen-test:633:21
            at logError (http://127.0.0.1:8000/wasm-bindgen-test:231:18)
            at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:8000/wasm-bindgen-test:632:66)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::Error::new::h0f3292be2f8d6e40 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3105]:0x1847aa)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook_impl::h5ccc83ef2fb241d3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1002]:0x123218)
            at web-fc40808d64b3182b.wasm.console_error_panic_hook::hook::h99d3469934819030 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[4469]:0x19abe8)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h5a5be30db70aa9af (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2717]:0x17b2e9)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x154293)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
        
        
    
    JS exception that was thrown:
        RuntimeError: unreachable
            at web-fc40808d64b3182b.wasm.__rust_start_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5419]:0x1a30cc)
            at web-fc40808d64b3182b.wasm.rust_panic (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5299]:0x1a2ba7)
            at web-fc40808d64b3182b.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1697]:0x1542be)
            at web-fc40808d64b3182b.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2227]:0x16ba13)
            at web-fc40808d64b3182b.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5397]:0x1a3033)
            at web-fc40808d64b3182b.wasm.rust_begin_unwind (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3314]:0x188b7a)
            at web-fc40808d64b3182b.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3475]:0x18bb9f)
            at web-fc40808d64b3182b.wasm.core::result::unwrap_failed::h472431483d5eea7f (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2487]:0x1748f6)
            at web-fc40808d64b3182b.wasm.web::test_scan::{{closure}}::hb68f83c66e78fce2 (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[156]:0x4b3a)
            at web-fc40808d64b3182b.wasm.wasm_bindgen_test::__rt::Context::execute_async::{{closure}}::hdf52bf0309b8b90a (http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[885]:0x11656f)

failures:

    web::test_scan_keys_by_index
    web::test_scan_by_index
    web::test_scan_keys
    web::test_scan

test result: FAILED. 13 passed; 4 failed; 0 ignored; 0 filtered out
```

**Comment by LucaCappelletti94** [comment]
From what I seem to understand, since [here](https://github.com/devashishdxt/deli/blob/6b68ee41541278a704ba40ce56df3dac5e6d4d06/deli/src/index.rs#L162) it executes `advance(1)` without checking any length, it would seem inevitable that it eventually goes out of bounds. That being said, before updating to the current version of idb, the problem does not present itself.

You may note that most likely the source of the problem is the same one, as all of the tests that are currently failing are related to calling `advance(1)`. Was there a change in `idb` regarding how advancing is handled?

**Comment by LucaCappelletti94** [comment]
Ok, now all tests are passing!

```
running 17 tests

test web::test_scan_keys_by_index ... ok
test web::test_scan_by_index ... ok
test web::test_get_all_keys_by_index ... ok
test web::test_get_all_by_index ... ok
test web::test_get_key_by_index ... ok
test web::test_get_by_index ... ok
test web::test_count_by_index ... ok
test web::test_unique_index ... ok
test web::test_delete ... ok
test web::test_scan_keys ... ok
test web::test_scan ... ok
test web::test_get_all_keys ... ok
test web::test_get_all ... ok
test web::test_count ... ok
test web::test_value_update ... ok
test web::test_value_add ... ok
test web::test_db_creation_and_deletion ... ok

test result: ok. 17 passed; 0 failed; 0 ignored; 0 filtered out

```

**Comment by devashishdxt** [comment]
You can use `ManagedCursor` from `idb` crate instead of adding that logic here.

**Comment by LucaCappelletti94** [comment]
Could you provide a short example using that?

**Comment by LucaCappelletti94** [comment]
Done! The test suite keeps passing.

**Review by devashishdxt — APPROVED** [review]

**Pull request merged**
